# Generated by Django 5.2.7 on 2025-11-11 02:17
from django.db import migrations

# Pega aquí tu SQL de datos "fijos" (regiones, comunidades, etc.).
# Recomendación: hazlo idempotente con ON CONFLICT DO NOTHING o WHERE NOT EXISTS.
SQL_SEED = """
-- =============================================
-- Carga inicial de REGIONES y COMUNIDADES
-- Fuente: 'DATOS REGIONES,COMUNIDADES.txt' (regiones + agrupación)
--          y Excel de COCODES (categoría -> tipo de comunidad)
-- Esquema destino: tablas 'regiones', 'tipos_comunidad', 'comunidades'
-- =============================================

BEGIN;

-- 1) Asegurar catálogo de tipos de comunidad (idempotente)
INSERT INTO tipos_comunidad (codigo, nombre) VALUES
    ('BAR','barrio'),
    ('CAS','caserío'),
    ('ALD','aldea'),
    ('MUN','municipio')
ON CONFLICT (codigo) DO NOTHING;

-- 2) Insertar/actualizar REGIONES (idempotente)
INSERT INTO regiones (codigo, nombre, comunidad_sede, descripcion)
VALUES
  ('REG-01', 'REGIÓN 1', 'EL CENTRO', 'Sede: Barrio El Centro'),
  ('REG-02', 'REGIÓN 2', 'MOCOHÁN', 'Sede: Aldea Mocohán'),
  ('REG-03', 'REGIÓN 3', 'LOS PINOS', 'Sede: Caserío Los Pinos'),
  ('REG-04', 'REGIÓN 4', 'EBEN-EZER', 'Sede: Aldea Eben-Ezer'),
  ('REG-05', 'REGIÓN 5', 'SUQUINAY II', 'Sede: Caserío Suquinay Ii'),
  ('REG-06', 'REGIÓN 6', 'SAN LUIS PANZAL', 'Sede: Caserío San Luis Panzal'),
  ('REG-07', 'REGIÓN 7', 'PANIMÁ', 'Sede: Aldea Panimá'),
  ('REG-08', 'REGIÓN 8', 'CENTRO PANCHISIVIC', 'Sede: Caserío Centro Panchisivic'),
  ('REG-09', 'REGIÓN 9', 'CHANTEL CHICOY', 'Sede: Aldea Chantel Chicoy'),
  ('REG-10', 'REGIÓN 10', 'RIBACÓ', 'Sede: Aldea Ribacó'),
  ('REG-11', 'REGIÓN 11', 'SAN MARCOS SACSAMANÍ', 'Sede: San Marcos Sacsamaní'),
  ('REG-12', 'REGIÓN 12', 'SACSAMANÍ', 'Sede: Aldea Sacsamaní'),
  ('REG-13', 'REGIÓN 13', 'LA PINADA', 'Sede: Aldea La Pinada'),
  ('REG-14', 'REGIÓN 14', 'CENTRO HELVETIA', 'Sede: Caserío Centro Helvetia'),
  ('REG-15', 'REGIÓN 15', 'MATANZAS', 'Sede: Aldea Matanzas'),
  ('REG-16', 'REGIÓN 16', 'NUEVO AMANECER PANCOC', 'Sede: Caserío Nuevo Amanecer Pancoc'),
  ('REG-17', 'REGIÓN 17', 'SIERRA LINDA', 'Sede: Caserío Sierra Linda')
ON CONFLICT (codigo) DO UPDATE
SET nombre=EXCLUDED.nombre,
    comunidad_sede=EXCLUDED.comunidad_sede,
    descripcion=EXCLUDED.descripcion;

-- 3) Insertar/actualizar COMUNIDADES (idempotente)
INSERT INTO comunidades (codigo, nombre, tipo_id, region_id)
VALUES
  ('R01-001', 'El Calvario', (SELECT id FROM tipos_comunidad WHERE nombre = 'barrio'), (SELECT id FROM regiones WHERE codigo = 'REG-01')),
  ('R01-002', 'El Carpintero', (SELECT id FROM tipos_comunidad WHERE nombre = 'barrio'), (SELECT id FROM regiones WHERE codigo = 'REG-01')),
  ('R01-003', 'El Cementerio', (SELECT id FROM tipos_comunidad WHERE nombre = 'barrio'), (SELECT id FROM regiones WHERE codigo = 'REG-01')),
  ('R01-004', 'El Centro', (SELECT id FROM tipos_comunidad WHERE nombre = 'barrio'), (SELECT id FROM regiones WHERE codigo = 'REG-01')),
  ('R01-005', 'La Cruz', (SELECT id FROM tipos_comunidad WHERE nombre = 'barrio'), (SELECT id FROM regiones WHERE codigo = 'REG-01')),
  ('R01-006', 'San Antonio', (SELECT id FROM tipos_comunidad WHERE nombre = 'barrio'), (SELECT id FROM regiones WHERE codigo = 'REG-01')),
  ('R01-007', 'Cerrito El Calvario', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-01')),
  ('R01-008', 'Cerro de La Cruz', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-01')),
  ('R01-009', 'La Cruz II', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-01')),
  ('R01-010', 'Los Encuentros', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-01')),
  ('R01-011', 'Barrio Las Moras', (SELECT id FROM tipos_comunidad WHERE nombre = 'barrio'), (SELECT id FROM regiones WHERE codigo = 'REG-01')),

  ('R02-001', 'Mocohan', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-02')),
  ('R02-002', 'El Durazno', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-02')),
  ('R02-003', 'Cola del Mico', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-02')),
  ('R02-004', 'Parrachoch I', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-02')),
  ('R02-005', 'Parrachoch II', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-02')),
  ('R02-006', 'Mocohan Sector II', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-02')),
  ('R02-007', 'Portezuelo', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-02')),
  ('R02-008', 'Betania', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-02')),
  ('R02-009', 'Pantin', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-02')),

  ('R03-001', 'Los Manantiales', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-03')),
  ('R03-002', 'Nueva Esperanza Cementerio', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-03')),
  ('R03-003', 'Panimaquito', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-03')),
  ('R03-004', 'Monjas Panimaquito', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-03')),
  ('R03-005', 'Rincón del Quetzal', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-03')),
  ('R03-006', 'Los Pinos', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-03')),
  ('R03-007', 'Cumbre del Carpintero', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-03')),
  ('R03-008', 'La Presa', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-03')),
  ('R03-009', 'Rincón El Carpintero', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-03')),
  ('R03-010', 'Cuchilla del Nogal', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-03')),
  ('R03-011', 'Río Colorado', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-03')),
  ('R03-012', 'Rincón Nueva Jerusalén', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-03')),

  ('R04-001', 'El Chorro', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-002', 'Agua Viva', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-003', 'Eben-Ezer', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-004', 'El Jute I', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-005', 'El Jute II', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-006', 'Chisiguan', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-007', 'Caserío El Mezcal I', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-008', 'El Pinal', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-009', 'El Repollal I', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-010', 'El Repollal II', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-011', 'Rincón del Suquinay', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-012', 'El Mirador Cerro Alto', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-013', 'Rincón El Calvario', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-014', 'Eben-Ezer II', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),
  ('R04-015', 'El Milagro', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-04')),

  ('R05-001', 'Bella Vista Sachut', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-05')),
  ('R05-002', 'Tierra Linda Sulín', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-05')),
  ('R05-003', 'Ronda Sachut', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-05')),
  ('R05-004', 'Tres Cruces', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-05')),
  ('R05-005', 'El Comunal', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-05')),
  ('R05-006', 'Villa Nueva Sulín', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-05')),
  ('R05-007', 'Suquinay II', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-05')),

  ('R06-001', 'Santa Rita Panzal', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-06')),
  ('R06-002', 'El Rosario Panzal', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-06')),
  ('R06-003', 'Orejuela', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-06')),
  ('R06-004', 'Herederos Panzal', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-06')),
  ('R06-005', 'Santa Elena Panzal', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-06')),
  ('R06-006', 'San Luis Panzal', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-06')),
  ('R06-007', 'Camelias Panzal', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-06')),
  ('R06-008', 'San Antonio Liquidambar', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-06')),
  ('R06-009', 'Canahan Panzal', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-06')),

  ('R07-001', 'La Ceiba', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-07')),
  ('R07-002', 'Monjón Panimá', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-07')),
  ('R07-003', 'San Miguel Panimá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-07')),
  ('R07-004', 'El Pacayal', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-07')),
  ('R07-005', 'San Luis Panimá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-07')),
  ('R07-006', 'Panimá', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-07')),
  ('R07-007', 'Los Ángeles Maxaxá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-07')),
  ('R07-008', 'Peña del Ángel', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-07')),
  ('R07-009', 'Santa Elena Panimá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-07')),

  ('R08-001', 'Nuevo Progreso Panchisivic', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-08')),
  ('R08-002', 'Concepción Panchisivic', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-08')),
  ('R08-003', 'Xombal Panchisivic', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-08')),
  ('R08-004', 'Sachoxá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-08')),
  ('R08-005', 'Santa Luisa Pancalá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-08')),
  ('R08-006', 'Cementerio Panchisivic', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-08')),
  ('R08-007', 'Centro Panchisivic', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-08')),
  ('R08-008', 'Esfuerzo Chejel', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-08')),
  ('R08-009', 'La Paz Chejel', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-08')),
  ('R08-010', 'La Caoba Panchisivic', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-08')),

  ('R09-001', 'El Carmen Los Gavilanes', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-09')),
  ('R09-002', 'Renacimiento Vega Larga I', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-09')),
  ('R09-003', 'Chantel Chicoy', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-09')),
  ('R09-004', 'San Pablo La Línea', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-09')),
  ('R09-005', 'Campo Nuevo Chicoy', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-09')),

  ('R10-001', 'Olimpia', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-10')),
  ('R10-002', 'Ribacó', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-10')),
  ('R10-003', 'Canaan Ribacó', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-10')),
  ('R10-004', 'Vista Hermosa', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-10')),
  ('R10-005', 'Los Naranjales', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-10')),
  ('R10-006', 'Cuchilla Jalanté', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-10')),
  ('R10-007', 'Sucursal Chicoy Panchisivic', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-10')),
  ('R10-008', 'Moxanté', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-10')),
  ('R10-009', 'Hamaca Panchisivic', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-10')),
  ('R10-010', 'Concepción Sector I Panchisivic', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-10')),
  ('R10-011', 'La Libertad Pampá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-10')),
  ('R10-012', 'Nuevo San Rafael Panchisivic', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-10')),

  ('R11-001', 'Panzal Jalauté', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-11')),
  ('R11-002', 'San Marcos Sacsamaní', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-11')),
  ('R11-003', 'Tierra Blanca Jalauté', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-11')),
  ('R11-004', 'Sector Norte Jalauté', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-11')),
  ('R11-005', 'El Carmen Villa Nueva Jalauté', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-11')),
  ('R11-006', 'Jalauté', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-11')),

  ('R12-001', 'Sacsamaní Panalbarda', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-12')),
  ('R12-002', 'Guachabajá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-12')),
  ('R12-003', 'Nuevo Jinayá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-12')),
  ('R12-004', 'Sacsamaní', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-12')),
  ('R12-005', 'Vega Larga II', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-12')),

  ('R13-001', 'Esquipulas La Pinada', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-13')),
  ('R13-002', 'Xejbal Monte Blanco', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-13')),
  ('R13-003', 'Cruz del Río Monte Blanco', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-13')),
  ('R13-004', 'San Antonio La Pinada', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-13')),
  ('R13-005', 'La Pinada', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-13')),
  ('R13-006', 'Nueva Esperanza Monte Blanco', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-13')),
  ('R13-007', 'Xalitzul Monte Blanco', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-13')),
  ('R13-008', 'Monte Blanco', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-13')),
  ('R13-009', 'EL Cementerio Monte Blanco', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-13')),
  ('R13-010', 'Sechinanjá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-13')),

  ('R14-001', 'Salijá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-14')),
  ('R14-002', 'San Pablo Helvetia', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-14')),
  ('R14-003', 'Cortéz La Cuchilla', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-14')),
  ('R14-004', 'Cabsibij', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-14')),
  ('R14-005', 'Centro Helvetia', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-14')),
  ('R14-006', 'Tixilhá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-14')),
  ('R14-007', 'San José Helvetia', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-14')),
  ('R14-008', 'Mululhá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-14')),

  ('R15-001', 'Crucero Helvetia', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-15')),
  ('R15-002', 'Centro Westfalia', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-15')),
  ('R15-003', 'Crucero Westfalia', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-15')),
  ('R15-004', 'Civijá', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-15')),
  ('R15-005', 'Civijá Sector I', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-15')),
  ('R15-006', 'Matucuy II', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-15')),
  ('R15-007', 'Matanzas', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-15')),
  ('R15-008', 'Matucuy I', (SELECT id FROM tipos_comunidad WHERE nombre = 'aldea'), (SELECT id FROM regiones WHERE codigo = 'REG-15')),
  ('R15-009', 'San Alfredo', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-15')),
  ('R15-010', 'Nueva Esperanza Westfalia', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-15')),
  ('R15-011', 'Centro Westfalia Sector II', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-15')),

  ('R16-001', 'Pampacay', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-16')),
  ('R16-002', 'Nueva Gloria', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-16')),
  ('R16-003', 'Concepción Las Flores', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-16')),
  ('R16-004', 'Monte Verde', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-16')),
  ('R16-005', 'Chacalté Pampacay', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-16')),
  ('R16-006', 'Nuevo Amanecer Pancoc', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-16')),
  ('R16-007', 'Cumbre Chacalté Jabalí', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-16')),
  ('R16-008', 'Nuevo San Rafael', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-16')),
  ('R16-009', 'Monte Alegre', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-16')),
  ('R16-010', 'Concepción El Espinero', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-16')),
  ('R16-011', 'Bethel Monte Verde', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-16')),
  ('R16-012', 'Finca Washington', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-16')),

  ('R17-001', 'Sierra Linda', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-17')),
  ('R17-002', 'Río Nuevo Chantelito', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-17')),
  ('R17-003', 'Santo Domingo Rio Blanco', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-17')),
  ('R17-004', 'Moxanté Cruz de Piedra', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-17')),
  ('R17-005', 'Villa Nueva Pancajoc', (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío'), (SELECT id FROM regiones WHERE codigo = 'REG-17'))
ON CONFLICT (codigo) DO UPDATE
SET nombre = EXCLUDED.nombre,
    tipo_id = EXCLUDED.tipo_id,
    region_id = EXCLUDED.region_id;

COMMIT;

-- Nota:
-- - Los registros de comunidad cuyo tipo no se encontró en el Excel quedan con tipo_id = NULL.
--   Puedes actualizarlos luego con:
--   UPDATE comunidades c SET tipo_id = (SELECT id FROM tipos_comunidad WHERE nombre = 'caserío')
--   WHERE c.codigo IN ('Rxx-yyy', ...);

-- =====================================================
-- USUARIOS DE PRUEBA PARA TESTING
-- =====================================================
-- Insertar puestos predefinidos (idempotente)
INSERT INTO puestos (codigo, nombre, descripcion) VALUES 
    ('GER', 'Gerente', 'Responsable de gestión y coordinación general'),
    ('CAP', 'Capacitador', 'Encargado de impartir capacitaciones'),
    ('COL', 'Colaborador', 'Personal de apoyo operativo')
ON CONFLICT (codigo) DO NOTHING;


INSERT INTO usuarios (
    username,
    email,
    telefono,
    password_hash,
    rol,
    puesto_id,
    activo
) VALUES (
    'admin',
    'admin@magapurulha.org',
    '12345678',
    crypt('Admin123@', gen_salt('bf')),
    'admin',
    NULL,  -- Admin NO tiene puesto
    TRUE
)
ON CONFLICT (username) DO NOTHING;


UPDATE usuarios SET nombre = 'Administrador del Sistema' WHERE username = 'admin';
--UPDATE usuarios SET email = 'jchendiaz15@gmail.com' WHERE username = 'juan.lopez';

-- =====================================================
-- SCRIPT PARA INSERTAR COLABORADORES
-- 1 Personal Fijo (vinculado a usuario existente) + 3 Colaboradores Externos
-- =====================================================

BEGIN;

-- =====================================================
-- 1. COLABORADOR PERSONAL FIJO (vinculado a usuario existente)
-- =====================================================


-- =====================================================
-- SCRIPT: ACTUALIZACIÓN DE COCODES Y TELÉFONOS (VERSIÓN ROBUSTA)
-- Maneja errores individualmente y verifica existencia
-- =====================================================

-- Primero, verificar qué comunidades existen
SELECT 
    codigo,
    nombre,
    CASE WHEN cocode IS NULL THEN 'Sin cocode' ELSE 'Con cocode' END as estado_actual
FROM comunidades
WHERE codigo LIKE 'R%'
ORDER BY codigo;

-- =====================================================
-- ACTUALIZACIONES CON MANEJO DE ERRORES
-- =====================================================

DO $$
DECLARE
    v_count INTEGER;
    v_error TEXT;
BEGIN
    -- REGIÓN 1
    UPDATE comunidades SET cocode = 'Miguel Miranda Chen', telefono_cocode = '4985-9326' WHERE codigo = 'R01-001';
    GET DIAGNOSTICS v_count = ROW_COUNT;
    IF v_count = 0 THEN RAISE NOTICE '⚠ R01-001 no encontrada'; END IF;
    
    UPDATE comunidades SET cocode = 'Miguel Caal Já', telefono_cocode = '5804-9354' WHERE codigo = 'R01-002';
    UPDATE comunidades SET cocode = 'Juan Fracisco Muz López', telefono_cocode = '5135-2900' WHERE codigo = 'R01-003';
    UPDATE comunidades SET cocode = 'Samuel Cuz Xol', telefono_cocode = '5152-8651' WHERE codigo = 'R01-004';
    UPDATE comunidades SET cocode = 'Edgar Geovany Sis Tiul', telefono_cocode = '4089-4034' WHERE codigo = 'R01-005';
    UPDATE comunidades SET cocode = 'Walter Otoniel López Paau', telefono_cocode = '3713-1540' WHERE codigo = 'R01-006';
    UPDATE comunidades SET cocode = 'José Ángel Chó López', telefono_cocode = '4049-9667' WHERE codigo = 'R01-007';
    UPDATE comunidades SET cocode = 'Rubén Catún Poou', telefono_cocode = '5315-4149' WHERE codigo = 'R01-008';
    UPDATE comunidades SET cocode = 'Jacinto Xoná Muz', telefono_cocode = '4980-7218' WHERE codigo = 'R01-009';
    UPDATE comunidades SET cocode = 'Rodolfo Caal Já', telefono_cocode = '4676-8254' WHERE codigo = 'R01-010';
    UPDATE comunidades SET cocode = 'Oscar Armando Yat', telefono_cocode = '5806-2801' WHERE codigo = 'R01-011';

    -- REGIÓN 2
    UPDATE comunidades SET cocode = 'Alfonzo Atzij', telefono_cocode = '5737-3083' WHERE codigo = 'R02-001';
    UPDATE comunidades SET cocode = 'Samuel Cucul Caal', telefono_cocode = '3330-4404' WHERE codigo = 'R02-002';
    UPDATE comunidades SET cocode = 'Jerónimo Vicente Tista González', telefono_cocode = '4495-0984' WHERE codigo = 'R02-003';
    UPDATE comunidades SET cocode = 'Baldomero González Tista', telefono_cocode = '3275-4744' WHERE codigo = 'R02-004';
    UPDATE comunidades SET cocode = 'Alejandro Tista Rodríguez', telefono_cocode = '4296-3849' WHERE codigo = 'R02-005';
    UPDATE comunidades SET cocode = 'Ricardo Caal Chá', telefono_cocode = '5229-7633' WHERE codigo = 'R02-006';
    UPDATE comunidades SET cocode = 'Ofelia Juc Caal', telefono_cocode = '4581-9044' WHERE codigo = 'R02-007';
    UPDATE comunidades SET cocode = 'Samuel Calel Caal', telefono_cocode = '4513-7995' WHERE codigo = 'R02-008';
    UPDATE comunidades SET cocode = 'Estela Caal', telefono_cocode = '4985-9379' WHERE codigo = 'R02-009';

    -- REGIÓN 3
    UPDATE comunidades SET cocode = 'Ricardo Sub Pop', telefono_cocode = '4080-1945' WHERE codigo = 'R03-001';
    UPDATE comunidades SET cocode = 'Fredy Leonel Asij Coy', telefono_cocode = '5388-3925' WHERE codigo = 'R03-002';
    UPDATE comunidades SET cocode = 'Abrahan Tut Ical', telefono_cocode = '3076-7787' WHERE codigo = 'R03-003';
    UPDATE comunidades SET cocode = 'Tiburcio Tipol Coy', telefono_cocode = '4592-0596' WHERE codigo = 'R03-004';
    UPDATE comunidades SET cocode = 'José Guillermo Xoc López', telefono_cocode = '4521-9092' WHERE codigo = 'R03-005';
    UPDATE comunidades SET cocode = 'Víctor Francisco Co Och', telefono_cocode = '3277-9064' WHERE codigo = 'R03-006';
    UPDATE comunidades SET cocode = 'Mario Choc Sel', telefono_cocode = '4841-0330' WHERE codigo = 'R03-007';
    UPDATE comunidades SET cocode = 'Filiberto Pop', telefono_cocode = '5736-0466' WHERE codigo = 'R03-008';
    UPDATE comunidades SET cocode = 'Héctor Alvarado Pop', telefono_cocode = '3747-5234' WHERE codigo = 'R03-009';
    UPDATE comunidades SET cocode = 'Eusebio Xoc', telefono_cocode = '5814-5246' WHERE codigo = 'R03-010';
    UPDATE comunidades SET cocode = 'Carlos Amílcar Gracia Sis', telefono_cocode = '5697-5256' WHERE codigo = 'R03-011';
    UPDATE comunidades SET cocode = 'Luis Alfredo Coy Arévalo', telefono_cocode = '4097-2265' WHERE codigo = 'R03-012';

    -- REGIÓN 4
    UPDATE comunidades SET cocode = 'Marcotulio Poou Pacay', telefono_cocode = '4846-8974' WHERE codigo = 'R04-001';
    UPDATE comunidades SET cocode = 'Álvaro Can', telefono_cocode = '3896-9070' WHERE codigo = 'R04-002';
    UPDATE comunidades SET cocode = 'Julio Pop', telefono_cocode = '5994-3781' WHERE codigo = 'R04-003';
    UPDATE comunidades SET cocode = 'Félix Ac Paau', telefono_cocode = '5581-1037' WHERE codigo = 'R04-004';
    UPDATE comunidades SET cocode = 'Cristóbal Can Rax', telefono_cocode = '3104-0481' WHERE codigo = 'R04-005';
    UPDATE comunidades SET cocode = 'Alejandro Cucul Can', telefono_cocode = '4544-9876' WHERE codigo = 'R04-006';
    UPDATE comunidades SET cocode = 'Gilberto Rolando Can López', telefono_cocode = '4782-2763' WHERE codigo = 'R04-007';
    UPDATE comunidades SET cocode = 'Miguel Pec', telefono_cocode = '3092-5683' WHERE codigo = 'R04-008';
    UPDATE comunidades SET cocode = 'Porfirio Ramiro Rax López', telefono_cocode = '3321-0164' WHERE codigo = 'R04-009';
    UPDATE comunidades SET cocode = 'Mateo Mez Si', telefono_cocode = '4029-4927' WHERE codigo = 'R04-010';
    UPDATE comunidades SET cocode = 'Elder Orlando Tot Rax', telefono_cocode = '4975-3428' WHERE codigo = 'R04-011';
    UPDATE comunidades SET cocode = 'Enrique Can Chó', telefono_cocode = NULL WHERE codigo = 'R04-012';
    UPDATE comunidades SET cocode = 'Julio Eriberto Iboy Ac', telefono_cocode = '3112-7257' WHERE codigo = 'R04-013';
    UPDATE comunidades SET cocode = 'Francisco Chub Tún', telefono_cocode = '4896-2918' WHERE codigo = 'R04-014';
    UPDATE comunidades SET cocode = NULL, telefono_cocode = NULL WHERE codigo = 'R04-015';

    -- REGIÓN 5
    UPDATE comunidades SET cocode = 'Héctor Efraín Tzib Xol', telefono_cocode = '5755-3746' WHERE codigo = 'R05-001';
    UPDATE comunidades SET cocode = 'Oliverio Cahuec', telefono_cocode = '3743-4122' WHERE codigo = 'R05-002';
    UPDATE comunidades SET cocode = 'Roberto Pérez Cahuec', telefono_cocode = '5353-9550' WHERE codigo = 'R05-003';
    UPDATE comunidades SET cocode = 'Genaro Poou Tut', telefono_cocode = '4890-1019' WHERE codigo = 'R05-004';
    UPDATE comunidades SET cocode = 'Laureliano Chún Cún', telefono_cocode = '4581-0988' WHERE codigo = 'R05-005';
    UPDATE comunidades SET cocode = 'Ernesto Chub Coy', telefono_cocode = '3051-5475' WHERE codigo = 'R05-006';
    UPDATE comunidades SET cocode = 'Edgar Vinicio Ac', telefono_cocode = '3337-0571' WHERE codigo = 'R05-007';

    -- REGIÓN 6
    UPDATE comunidades SET cocode = 'Matin Pou Quej', telefono_cocode = '4542-9547' WHERE codigo = 'R06-001';
    UPDATE comunidades SET cocode = 'Samuel Lem Tut', telefono_cocode = '4985-9014' WHERE codigo = 'R06-002';
    UPDATE comunidades SET cocode = 'Mauricio Gercía Pop', telefono_cocode = '3166-0784' WHERE codigo = 'R06-003';
    UPDATE comunidades SET cocode = 'Baldomero Pop Maas', telefono_cocode = '3304-9691' WHERE codigo = 'R06-004';
    UPDATE comunidades SET cocode = 'Julian Quej Cabnal', telefono_cocode = '3234-6119' WHERE codigo = 'R06-005';
    UPDATE comunidades SET cocode = 'Hilda Ofelia Cahuec Quej De Pop', telefono_cocode = '5033-7861' WHERE codigo = 'R06-006';
    UPDATE comunidades SET cocode = 'Fernando Lep Chén', telefono_cocode = '5329-3236' WHERE codigo = 'R06-007';
    UPDATE comunidades SET cocode = 'Otoniel David Tul Ichich', telefono_cocode = '5380-6517' WHERE codigo = 'R06-008';
    UPDATE comunidades SET cocode = 'Marla Adelina Ayú Caal', telefono_cocode = '5304-1185' WHERE codigo = 'R06-009';

    -- REGIÓN 7
    UPDATE comunidades SET cocode = 'Eliseo Ampérez', telefono_cocode = '4893-8256' WHERE codigo = 'R07-001';
    UPDATE comunidades SET cocode = 'Isaac Cacao Ché', telefono_cocode = '3272-0177' WHERE codigo = 'R07-002';
    UPDATE comunidades SET cocode = 'Adolfo Cacao Chón', telefono_cocode = '4626-1911' WHERE codigo = 'R07-003';
    UPDATE comunidades SET cocode = 'Sebastián Lucas Tut', telefono_cocode = '5352-3648' WHERE codigo = 'R07-004';
    UPDATE comunidades SET cocode = 'Liberardo Cahuec Juc', telefono_cocode = '4015-5970' WHERE codigo = 'R07-005';
    UPDATE comunidades SET cocode = 'Rodolfo Caal Chón', telefono_cocode = '4862-9384' WHERE codigo = 'R07-006';
    UPDATE comunidades SET cocode = 'Enrique Maas Franco', telefono_cocode = '3743-7569' WHERE codigo = 'R07-007';
    UPDATE comunidades SET cocode = 'Samuel López Velasquez', telefono_cocode = '4777-5537' WHERE codigo = 'R07-008';
    UPDATE comunidades SET cocode = 'Marco Antonio Ichich Caal', telefono_cocode = '3014-1126' WHERE codigo = 'R07-009';

    -- REGIÓN 8
    UPDATE comunidades SET cocode = 'Marcos Chen Chub', telefono_cocode = '3202-9806' WHERE codigo = 'R08-001';
    UPDATE comunidades SET cocode = 'Mateo Ichich', telefono_cocode = '3277-8432' WHERE codigo = 'R08-002';
    UPDATE comunidades SET cocode = 'Horoldo Juc Morán', telefono_cocode = '3027-1159' WHERE codigo = 'R08-003';
    UPDATE comunidades SET cocode = 'Rodrigo Cú Juc', telefono_cocode = '4821-1848' WHERE codigo = 'R08-004';
    UPDATE comunidades SET cocode = 'Antonio Ixim', telefono_cocode = '3113-0089' WHERE codigo = 'R08-005';
    UPDATE comunidades SET cocode = 'Nasario Quej', telefono_cocode = '4935-1644' WHERE codigo = 'R08-006';
    UPDATE comunidades SET cocode = 'Samuel Chiquin Ichic', telefono_cocode = '4037-1495' WHERE codigo = 'R08-007';
    UPDATE comunidades SET cocode = 'Carlos Humberto Tzib Ac', telefono_cocode = '5196-6958' WHERE codigo = 'R08-008';
    UPDATE comunidades SET cocode = 'Gabino Chá', telefono_cocode = '4079-7180' WHERE codigo = 'R08-009';
    UPDATE comunidades SET cocode = 'Nazario Cal Morán', telefono_cocode = '5371-6451' WHERE codigo = 'R08-010';

    -- REGIÓN 9
    UPDATE comunidades SET cocode = 'Mario Coy Iquí', telefono_cocode = '4582-8388' WHERE codigo = 'R09-001';
    UPDATE comunidades SET cocode = 'Roberto Iquí Ichich', telefono_cocode = '4057-4214' WHERE codigo = 'R09-002';
    UPDATE comunidades SET cocode = 'Carlos Ichich Yat', telefono_cocode = '5809-8954' WHERE codigo = 'R09-003';
    UPDATE comunidades SET cocode = 'Ribén Xol', telefono_cocode = '4677-2567' WHERE codigo = 'R09-004';
    UPDATE comunidades SET cocode = 'Julio Cal Tziboy', telefono_cocode = '5768-1022' WHERE codigo = 'R09-005';

    -- REGIÓN 10
    UPDATE comunidades SET cocode = 'Alfredo Cún Och', telefono_cocode = '4019-1663' WHERE codigo = 'R10-001';
    UPDATE comunidades SET cocode = 'Esteban Santiago Caal Iquí', telefono_cocode = '4543-3049' WHERE codigo = 'R10-002';
    UPDATE comunidades SET cocode = 'Mario Ichich Caal', telefono_cocode = '4981-8038' WHERE codigo = 'R10-003';
    UPDATE comunidades SET cocode = 'Salvador Ichich Ichich', telefono_cocode = '5061-4703' WHERE codigo = 'R10-004';
    UPDATE comunidades SET cocode = 'Mario Caal Ichich', telefono_cocode = '5000-5254' WHERE codigo = 'R10-005';
    UPDATE comunidades SET cocode = 'Alfredo Já', telefono_cocode = '4915-0876' WHERE codigo = 'R10-006';
    UPDATE comunidades SET cocode = 'Miguel Choc Quej', telefono_cocode = '3323-1216' WHERE codigo = 'R10-007';
    UPDATE comunidades SET cocode = 'Emilio Cacao Iquí', telefono_cocode = '4998-8090' WHERE codigo = 'R10-008';
    UPDATE comunidades SET cocode = 'Jorge Luis Pop Ichic', telefono_cocode = '4825-5438' WHERE codigo = 'R10-009';
    UPDATE comunidades SET cocode = 'Rigoberto Chá Saguí', telefono_cocode = '5200-7210' WHERE codigo = 'R10-010';
    UPDATE comunidades SET cocode = 'Mario Arturo Ixim Ichich', telefono_cocode = '3880-8142' WHERE codigo = 'R10-011';
    UPDATE comunidades SET cocode = 'Hermelindo Toc Ichich', telefono_cocode = '3007-8238' WHERE codigo = 'R10-012';

    -- REGIÓN 11
    UPDATE comunidades SET cocode = 'Faustina Cal Juc', telefono_cocode = '4585-5937' WHERE codigo = 'R11-001';
    UPDATE comunidades SET cocode = 'Lorenzo Choc', telefono_cocode = '5372-3021' WHERE codigo = 'R11-002';
    UPDATE comunidades SET cocode = 'Ramiro Felipe Sanchez', telefono_cocode = '4060-8425' WHERE codigo = 'R11-003';
    UPDATE comunidades SET cocode = 'Erwin Leonel Coy Caal', telefono_cocode = '3130-9302' WHERE codigo = 'R11-004';
    UPDATE comunidades SET cocode = 'Carlos Victoriano Cal Ical', telefono_cocode = '4045-5320' WHERE codigo = 'R11-005';
    UPDATE comunidades SET cocode = 'Juan Pablo Leonardo Pop Cacao', telefono_cocode = '3011-4947' WHERE codigo = 'R11-006';

    -- REGIÓN 12
    UPDATE comunidades SET cocode = 'Efraín Iquí Ichich', telefono_cocode = '4909-0801' WHERE codigo = 'R12-001';
    UPDATE comunidades SET cocode = 'Juan José Tziboy Caal', telefono_cocode = '4669-2003' WHERE codigo = 'R12-002';
    UPDATE comunidades SET cocode = 'Mauro Chú Coc', telefono_cocode = '5038-7663' WHERE codigo = 'R12-003';
    UPDATE comunidades SET cocode = 'Oscar Francisco Má Quej', telefono_cocode = '5883-6733' WHERE codigo = 'R12-004';
    UPDATE comunidades SET cocode = 'Manuel Iquí Caal', telefono_cocode = '4523-0012' WHERE codigo = 'R12-005';

    -- REGIÓN 13
    UPDATE comunidades SET cocode = 'Guillermo Já Iquí', telefono_cocode = '4080-4796' WHERE codigo = 'R13-001';
    UPDATE comunidades SET cocode = 'Roberto Caal Choc', telefono_cocode = '4898-8888' WHERE codigo = 'R13-002';
    UPDATE comunidades SET cocode = 'Elías Morán Ichich', telefono_cocode = '4020-8900' WHERE codigo = 'R13-003';
    UPDATE comunidades SET cocode = 'Pedro Juc Coc', telefono_cocode = '4993-4265' WHERE codigo = 'R13-004';
    UPDATE comunidades SET cocode = 'Guillermo Cú Cun', telefono_cocode = '4958-5903' WHERE codigo = 'R13-005';
    UPDATE comunidades SET cocode = 'Ángel Gabriel Sacbá Sun', telefono_cocode = '5897-3780' WHERE codigo = 'R13-006';
    UPDATE comunidades SET cocode = 'Ottoniel Sagui Chub', telefono_cocode = '3740-2682' WHERE codigo = 'R13-007';
    UPDATE comunidades SET cocode = 'Camilo Xol Caal', telefono_cocode = '5201-8741' WHERE codigo = 'R13-008';
    UPDATE comunidades SET cocode = 'Marco Antonio Coc', telefono_cocode = '4776-3473' WHERE codigo = 'R13-009';
    UPDATE comunidades SET cocode = 'Arnoldo Cú', telefono_cocode = NULL WHERE codigo = 'R13-010';

    -- REGIÓN 14
    UPDATE comunidades SET cocode = 'Héctor Xol Ical', telefono_cocode = '5373-7921' WHERE codigo = 'R14-001';
    UPDATE comunidades SET cocode = 'Armando Choc Chalib', telefono_cocode = '3074-3393' WHERE codigo = 'R14-002';
    UPDATE comunidades SET cocode = 'Enrique Tzí Cú', telefono_cocode = NULL WHERE codigo = 'R14-003';
    UPDATE comunidades SET cocode = 'Rodolfo Saguí Cuc', telefono_cocode = '3838-8397' WHERE codigo = 'R14-004';
    UPDATE comunidades SET cocode = 'Héctor Abel Chá Franco', telefono_cocode = '4560-9039' WHERE codigo = 'R14-005';
    UPDATE comunidades SET cocode = 'Gérman Caal', telefono_cocode = '4507-4199' WHERE codigo = 'R14-006';
    UPDATE comunidades SET cocode = 'Aurelio Mistí Chá', telefono_cocode = '4564-7674' WHERE codigo = 'R14-007';
    UPDATE comunidades SET cocode = 'Héctor Jó Caal', telefono_cocode = '3261-3040' WHERE codigo = 'R14-008';

    -- REGIÓN 15
    UPDATE comunidades SET cocode = 'Arturo Ché Reyes', telefono_cocode = '5994-0401' WHERE codigo = 'R15-001';
    UPDATE comunidades SET cocode = 'Víctor Manuel Mucú Cuc', telefono_cocode = '3751-3001' WHERE codigo = 'R15-002';
    UPDATE comunidades SET cocode = 'Juán Tiul', telefono_cocode = '3199-9122' WHERE codigo = 'R15-003';
    UPDATE comunidades SET cocode = 'Oscar Maquin Xí', telefono_cocode = '3360-2296' WHERE codigo = 'R15-004';
    UPDATE comunidades SET cocode = 'Felipe Cuc Rax', telefono_cocode = '4039-9894' WHERE codigo = 'R15-005';
    UPDATE comunidades SET cocode = 'Víctor Manuel Chub Sacba', telefono_cocode = '4022-3921' WHERE codigo = 'R15-006';
    UPDATE comunidades SET cocode = 'Egidio Sam Ical', telefono_cocode = '5033-4284' WHERE codigo = 'R15-007';
    UPDATE comunidades SET cocode = 'Fermín Maquin', telefono_cocode = '3029-6955' WHERE codigo = 'R15-008';
    UPDATE comunidades SET cocode = 'Mario Mistí', telefono_cocode = '4643-5386' WHERE codigo = 'R15-009';
    UPDATE comunidades SET cocode = 'Hermelindo Xí Maquín', telefono_cocode = '5706-5581' WHERE codigo = 'R15-010';
    UPDATE comunidades SET cocode = 'Alfredo Rax Cú', telefono_cocode = '5180-3524' WHERE codigo = 'R15-011';

    -- REGIÓN 16
    UPDATE comunidades SET cocode = 'Ismael Pop', telefono_cocode = '5321-7017' WHERE codigo = 'R16-001';
    UPDATE comunidades SET cocode = 'Lucas Quej', telefono_cocode = '3178-9525' WHERE codigo = 'R16-002';
    UPDATE comunidades SET cocode = 'Valerio Rodolfo Má Ical', telefono_cocode = '4856-8543' WHERE codigo = 'R16-003';
    UPDATE comunidades SET cocode = 'Genaro Teyul Ac', telefono_cocode = '4569-5843' WHERE codigo = 'R16-004';
    UPDATE comunidades SET cocode = 'Valeriano Choc', telefono_cocode = '4982-9109' WHERE codigo = 'R16-005';
    UPDATE comunidades SET cocode = 'Juan Gabriel Juc Coy', telefono_cocode = '4019-8540' WHERE codigo = 'R16-006';
    UPDATE comunidades SET cocode = 'Julio Amílcar Caal Coy', telefono_cocode = '4798-7162' WHERE codigo = 'R16-007';
    UPDATE comunidades SET cocode = 'Guadalupe Laj', telefono_cocode = '3295-8902' WHERE codigo = 'R16-008';
    UPDATE comunidades SET cocode = 'Ricardo Alfredo García', telefono_cocode = '4512-6027' WHERE codigo = 'R16-009';
    UPDATE comunidades SET cocode = 'Ambrocio Ichich Caal', telefono_cocode = '3700-5895' WHERE codigo = 'R16-010';
    UPDATE comunidades SET cocode = 'Genaro Teyul Ac', telefono_cocode = '3319-6264' WHERE codigo = 'R16-011';

    -- REGIÓN 17
    UPDATE comunidades SET cocode = 'Adelso Cahuec Ichich', telefono_cocode = '4635-3471' WHERE codigo = 'R17-001';
    UPDATE comunidades SET cocode = 'Oscar Alberto Caal Coy', telefono_cocode = '4905-1490' WHERE codigo = 'R17-002';
    UPDATE comunidades SET cocode = 'Santos Saguí Cahuec', telefono_cocode = '5183-5570' WHERE codigo = 'R17-003';
    UPDATE comunidades SET cocode = 'Margarito Cun Iquí', telefono_cocode = '5522-6594' WHERE codigo = 'R17-004';
    -- R17-005 no tiene cocode según el listado

    RAISE NOTICE '✅ Actualizaciones completadas';
    
EXCEPTION WHEN OTHERS THEN
    GET STACKED DIAGNOSTICS v_error = MESSAGE_TEXT;
    RAISE NOTICE '❌ Error: %', v_error;
    RAISE;
END $$;


"""

# Opcional: cómo revertir esos datos. Si no quieres borrar nada, deja SELECT 1;
REVERSE_SQL = """
-- Ejemplo de delete si quisieras revertir (borra si no aplica):
-- DELETE FROM regiones WHERE nombre IN ('Alta Verapaz','Baja Verapaz');
SELECT 1;
"""

class Migration(migrations.Migration):
    dependencies = [
        ('webmaga', '0005_usuariofotoperfil'),
        ('webmaga', '0002_db_objects'),
    ]

    # Pon False solo si fueras a usar operaciones que no permiten transacción
    atomic = True

    operations = [
        migrations.RunSQL(sql=SQL_SEED, reverse_sql=REVERSE_SQL),
    ]

