"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")  # carga variables

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('KEY_DJANGO')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Hosts permitidos (separados por coma en .env)
ALLOWED_HOSTS = ['*']
# Origenes confiables para CSRF (para HTTPS)
CSRF_TRUSTED_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if os.getenv('CSRF_TRUSTED_ORIGINS') else []

#ENVIO DE CORREOS
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '20'))
ASISTENCIA_CONTACT_EMAIL = os.environ.get('ASISTENCIA_CONTACT_EMAIL', EMAIL_HOST_USER or 'recupmagabvpurulha@gmail.com')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',  # Soporte para características específicas de PostgreSQL
    'webmaga.apps.WebmagaConfig',  # Configuración personalizada que crea carpetas de media automáticamente
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'webmaga.middleware.NoCacheMiddleware',  # Agregar headers de no-cache para páginas autenticadas
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "src" / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'webmaga.context_processors.usuario_maga',  # Context processor personalizado
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'OPTIONS': {
            'options': '-c timezone=America/Guatemala'  # Forzar zona horaria en cada conexión
        },
    }
}

# =====================================================
# CONFIGURACIÓN DE CACHÉ (para mejorar rendimiento)
# =====================================================
# Usando caché en memoria local (no requiere Redis ni Memcached)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'webmaga-cache',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,  # Máximo de entradas en caché
        }
    }
}

# Tiempo de caché por defecto (5 minutos)
CACHE_MIDDLEWARE_SECONDS = 300


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Backend de autenticación personalizado
AUTHENTICATION_BACKENDS = [
    'webmaga.authentication.UsuarioMAGABackend',  # Backend personalizado para tabla usuarios
    'django.contrib.auth.backends.ModelBackend',  # Backend por defecto de Django
]

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# URLs de autenticación
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Configuración de sesiones
# La sesión durará una semana (7 días) y no se cerrará al cerrar el navegador
# IMPORTANTE: Esta configuración asegura que la sesión persista en Android incluso al cerrar la app
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # No cerrar sesión al cerrar el navegador (crítico para Android)
SESSION_COOKIE_AGE = 604800  # 7 días en segundos (7 * 24 * 60 * 60 = 604800)
SESSION_SAVE_EVERY_REQUEST = True  # Renovar la sesión con cada solicitud para mantenerla activa
SESSION_COOKIE_HTTPONLY = True  # Seguridad: evitar acceso desde JavaScript
SESSION_COOKIE_SAMESITE = 'Lax'  # Protección CSRF
# Configuración adicional para Android: asegurar que las cookies sean persistentes
SESSION_COOKIE_NAME = 'sessionid'  # Nombre estándar de Django
# No establecer SESSION_COOKIE_DOMAIN para que funcione en todos los subdominios si es necesario
# SESSION_COOKIE_PATH = '/'  # Por defecto ya es '/'


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-gt'  # Español de Guatemala

TIME_ZONE = 'America/Guatemala'  # Zona horaria de Guatemala (UTC-6)

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "src" / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Archivos subidos por usuarios
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# =====================================================
# CONFIGURACIÓN DE COMPRESIÓN DE IMÁGENES
# =====================================================
COMPRESS_IMAGES = True 

# Configuraciones por tipo de imagen
IMAGE_COMPRESSION_SETTINGS = {
    'profile': {
        'max_width': 1200,      
        'max_height': 1200,
        'quality': 80,          
        'format_output': 'JPEG',
        'min_size_kb': 300      
    },
    'gallery': {
        'max_width': 1920,      
        'max_height': 1080,
        'quality': 85,
        'format_output': 'JPEG',
        'min_size_kb': 400
    },
    'evidence': {
        'max_width': 1920,      
        'max_height': 1080,
        'quality': 80,          
        'format_output': 'JPEG',
        'min_size_kb': 500
    },
    'thumbnail': {
        'max_width': 400,
        'max_height': 400,
        'quality': 85,
        'format_output': 'JPEG',
        'min_size_kb': 100
    },
    'default': {
        'max_width': 1920,
        'max_height': 1080,
        'quality': 80,
        'format_output': 'JPEG',
        'min_size_kb': 300
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =====================================================
# CONFIGURACIONES DE SEGURIDAD PARA PRODUCCIÓN
# =====================================================
# Se activan automáticamente cuando DEBUG=False

if not DEBUG:
    # Configurar proxy reverso (Dokploy/Traefik)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # Forzar HTTPS
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Seguridad adicional
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
